FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ENV LANG=nb_NO.UTF-8

RUN set -eux; \
    apt-get update; \
    apt-get install --no-install-recommends -y \
      ca-certificates \
      curl \
      iputils-ping \
      ldapscripts \
      samba \
      smbldap-tools \
      vim \
    ; \
    rm -rf /var/lib/apt/lists/*
