- name: Ensure config directory exists
  file:
    path: /opt/mysql-2
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Copy config file
  copy:
    dest: /opt/mysql-2/custom.cnf
    src: custom.cnf
    owner: root
    group: root
    mode: 0644
  register: file_copied

- name: Start mysql container
  docker_container:
    name: mysql-2
    state: started
    image: "{{ mysql_2_image }}"
    restart_policy: unless-stopped
    env:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - name: fbs0
        ipv4_address: "{{ mysql_2_ipv4_address }}"
    networks_cli_compatible: yes
    volumes:
      - /data/mysql-2-data:/var/lib/mysql
      - /opt/mysql-2/custom.cnf:/etc/mysql/conf.d/custom.cnf
    log_driver: journald
    restart: "{{ file_copied.changed }}"
