desired_hostname: coreos-4.foreningenbs.no

zerotier_host_ip: "172.25.11.4"
zerotier_host_ip_cidr: "172.25.11.4/16"
zerotier_network_id: a84ac5c10a9c7522

docker_subnet: "172.25.0.0/16"
docker_ip_range: "172.25.24.1/24"

host_type: coreos
data_dir: /data
