coreos_hostname: coreos-3.foreningenbs.no

fbs_dyndns_name: fbs-coreos-3
zerotier_host_ip: "172.25.11.3"
zerotier_host_ip_cidr: "172.25.11.3/16"
zerotier_network_id: a84ac5c10a9c7522

docker_subnet: "172.25.0.0/16"
docker_ip_range: "172.25.23.1/24"
