name: Setup SSH
inputs:
  ssh-private-key:
    description: 'SSH private key'
    required: true
runs:
  using: composite
  steps:
    - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
    - run: ssh-add -l
      shell: bash
    - run: cat .github/known_hosts >>~/.ssh/known_hosts
      shell: bash
    - run: cp .github/sshconfig ~/.ssh/config
      shell: bash
