- name: Ensure config directory exists
  file:
    path: /var/ansible/mongodb-1
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Copy config file
  copy:
    dest: /var/ansible/mongodb-1/mongod.yml
    src: mongod.yml
    owner: root
    group: root
    mode: 0644
  register: file_copied

- name: Start mongodb container
  docker_container:
    name: mongodb-1
    state: started
    image: "{{ mongodb_1_image }}"
    restart_policy: unless-stopped
    networks:
      - name: fbs0
        ipv4_address: "{{ mongodb_1_ipv4_address }}"
    networks_cli_compatible: yes
    volumes:
      - /var/ansible/mongodb-1/mongod.yml:/mongod.yml:Z
      - /var/mnt/data/mongodb-1-db:/data/db:Z
      - /var/mnt/data/mongodb-1-configdb:/data/configdb:Z
    log_driver: journald
    restart: "{{ file_copied.changed }}"
    command: --config /mongod.yml
