version: "3.7"

services:
  ldap-toolbox:
    build: .
    image: ldap-toolbox
    # Keep running in the background.
    tty: true
    volumes:
      - /var/mnt/data:/data
      - /var/mnt/data/drift:/fbs/drift:z
      - ../certs/ca.crt:/etc/fbs-ca.crt:z
      - ./container/ldap.conf:/etc/ldap/ldap.conf:z
      - ./container/ldapscripts.conf:/etc/ldapscripts/ldapscripts.conf:z
      - ./container/ldapadduser.template:/etc/ldapscripts/ldapadduser.template:z
      - ./container/ldapscripts.passwd:/etc/ldapscripts/ldapscripts.passwd:z
      - ./container/smbldap_bind.conf:/etc/smbldap-tools/smbldap_bind.conf:z
      - ./container/smbldap.conf:/etc/smbldap-tools/smbldap.conf:z
    working_dir: /data/intern-backend-data/user-requests

networks:
  default:
    external:
      name: fbs0
