version: "3.7"

services:
  ldap-toolbox:
    build: .
    image: ldap-toolbox
    # Keep running in the background.
    tty: true
    volumes:
      - /var/mnt/data:/data:Z
      - /var/mnt/data/drift:/fbs/drift:Z
      - ../certs/ca.crt:/etc/fbs-ca.crt:Z
      - ./container/ldap.conf:/etc/ldap/ldap.conf:Z
      - ./container/ldapscripts.conf:/etc/ldapscripts/ldapscripts.conf:Z
      - ./container/ldapadduser.template:/etc/ldapscripts/ldapadduser.template:Z
      - ./container/ldapscripts.passwd:/etc/ldapscripts/ldapscripts.passwd:Z
      - ./container/smbldap_bind.conf:/etc/smbldap-tools/smbldap_bind.conf:Z
      - ./container/smbldap.conf:/etc/smbldap-tools/smbldap.conf:Z
    working_dir: /data/web-1-www/users

networks:
  default:
    external:
      name: fbs0
