version: '2'

services:
  okoreports-backend:
    image: cybrairai/okoreports-backend
    restart: unless-stopped
    volumes:
      - okoreports-reports:/var/okoreports/reports
      - ./settings.py:/usr/src/tripletex/settings_local.py
    ports:
      - '127.0.0.1:8051:8000'

  okoreports-frontend:
    image: cybrairai/okoreports-frontend
    restart: unless-stopped
    ports:
      - '127.0.0.1:8050:80'

volumes:
  okoreports-reports:
