- name: Ensure config directory exists
  file:
    path: /opt/ldap-master
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Copy cert files (1/2)
  copy:
    dest: /opt/ldap-master/
    src: "{{ playbook_dir }}/../certs/{{ item }}"
    owner: "1000"
    group: "1000"
    mode: 0644
  with_items:
    - ca.crt
    - dhparam.pem
  register: file_copied1

- name: Copy cert files (2/2)
  copy:
    dest: /opt/ldap-master/
    src: "{{ playbook_dir }}/../certs/ldap/{{ item }}"
    owner: "1000"
    group: "1000"
    mode: 0644
  with_items:
    - ldap-master.crt
    - ldap-master.key
  register: file_copied2

- name: Start ldap-master container
  docker_container:
    name: ldap-master
    state: started
    image: "{{ ldap_master_image }}"
    restart_policy: unless-stopped
    env:
      # Uncomment for debugging.
      # LDAP_LOG_LEVEL: "-1"
    networks:
      - name: fbs0
        ipv4_address: "{{ ldap_master_ipv4_address }}"
    networks_cli_compatible: yes
    hostname: ldap-master.zt.foreningenbs.no
    volumes:
      - /data/ldap-master-data:/var/lib/ldap
      - /data/ldap-master-config:/etc/ldap/slapd.d
      - /opt/ldap-master/dhparam.pem:/certs/dhparam.pem
      - /opt/ldap-master/ca.crt:/certs/ca.crt
      - /opt/ldap-master/ldap-master.crt:/certs/slapd.crt
      - /opt/ldap-master/ldap-master.key:/certs/slapd.key
    log_driver: journald
    restart: "{{ file_copied1.changed or file_copied2.changed }}"
