# TYPE  DATABASE        USER            ADDRESS         METHOD
local      all           all                             trust
# pgadmin: auth handled by SAML on foreningenbs.no/tools
host       all           all             172.25.16.57/32 trust
host       all           all             all             scram-sha-256
