---
version: '3'

services:
  users-api:
    image: blindern/smaabruket-availability-api:$SMAABRUKET_AVAILABILITY_API_TAG
    ports:
      - 8001:8000
    env_file:
      - variables.env
    working_dir: /app
    restart: unless-stopped
    logging:
      driver: journald
