- name: Ensure config directory exists
  file:
    path: /var/ansible/uka-billett
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Copy config files
  copy:
    dest: "/var/ansible/uka-billett/{{ item }}"
    src: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - fpm-secrets.env
    - database.php
    - nginx-secrets.env
  register: file_copied

# This is considered temporary. Ideally we want to rework how
# we build and deploy the system.
- name: Clone billett repo
  git:
    repo: https://github.com/blindernuka/billett.git
    dest: /var/ansible/uka-billett/billett-repo
  register: repo_cloned

- name: Start uka-billett-fpm container
  docker_container:
    name: uka-billett-fpm
    state: started
    image: "{{ uka_billett_fpm_image }}"
    restart_policy: unless-stopped
    networks:
      - name: fbs0
        ipv4_address: "{{ uka_billett_fpm_ipv4_address }}"
    networks_cli_compatible: yes
    env_file: /var/ansible/uka-billett/fpm-secrets.env
    hostname: uka-billett-fpm.zt.foreningenbs.no
    volumes:
      - /var/mnt/data/uka-billett-data:/var/billett:Z
      # Keeping an override here to avoid having to rebuild the image for now.
      - /var/ansible/uka-billett/database.php:/var/www/html/app/config/prod/database.php:Z
    log_driver: journald
    restart: "{{ file_copied.changed }}"

- name: Start uka-billett-nginx container
  docker_container:
    name: uka-billett-nginx
    state: started
    image: "{{ uka_billett_nginx_image }}"
    restart_policy: unless-stopped
    networks:
      - name: fbs0
        ipv4_address: "{{ uka_billett_nginx_ipv4_address }}"
    networks_cli_compatible: yes
    env_file: /var/ansible/uka-billett/nginx-secrets.env
    hostname: uka-billett-nginx.zt.foreningenbs.no
    volumes:
      - /var/mnt/data/uka-billett-frontend-dist:/var/www/billett-frontend-dist:Z
      - /var/ansible/uka-billett/billett-repo/nginx/nginx.conf:/etc/nginx/nginx.conf:Z
      - /var/ansible/uka-billett/billett-repo/nginx/default.conf:/etc/nginx/conf.d/default.conf.template:Z
    log_driver: journald
    restart: "{{ file_copied.changed or repo_cloned.changed }}"
    command: /bin/sh -c "envsubst '$${PRERENDER_TOKEN}' </etc/nginx/conf.d/default.conf.template >/etc/nginx/conf.d/default.conf && sed -i 's/fpm:9000/uka-billett-fpm.zt.foreningenbs.no:9000/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
