- name: Ensure config directory exists
  file:
    path: /var/ansible/uka-billett
    state: directory
    owner: root
    group: root
    mode: 0700

# TODO: Remove orphan /var/ansible/uka-billett/database.php

- name: Copy config files
  copy:
    dest: "/var/ansible/uka-billett/{{ item }}"
    src: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - fpm-secrets.env
    - nginx.env
  register: file_copied

- name: Start uka-billett-fpm container
  docker_container:
    name: uka-billett-fpm
    state: started
    image: "{{ uka_billett_fpm_image }}"
    restart_policy: unless-stopped
    networks:
      - name: fbs0
        ipv4_address: "{{ uka_billett_fpm_ipv4_address }}"
    networks_cli_compatible: yes
    env_file: /var/ansible/uka-billett/fpm-secrets.env
    hostname: uka-billett-fpm.zt.foreningenbs.no
    volumes:
      - /var/mnt/data/uka-billett-data:/var/www/html/storage:z
    log_driver: journald
    restart: "{{ file_copied.changed }}"

- name: Start uka-billett-proxy container
  docker_container:
    name: uka-billett-proxy
    state: started
    image: "{{ uka_billett_proxy_image }}"
    restart_policy: unless-stopped
    networks:
      - name: fbs0
        ipv4_address: "{{ uka_billett_proxy_ipv4_address }}"
    networks_cli_compatible: yes
    hostname: uka-billett-proxy.zt.foreningenbs.no
    log_driver: journald
    env_file: /var/ansible/uka-billett/nginx.env

- name: Start uka-billett-frontend container
  docker_container:
    name: uka-billett-frontend
    state: started
    image: "{{ uka_billett_frontend_image }}"
    restart_policy: unless-stopped
    networks:
      - name: fbs0
        ipv4_address: "{{ uka_billett_frontend_ipv4_address }}"
    networks_cli_compatible: yes
    hostname: uka-billett-frontend.zt.foreningenbs.no
    log_driver: journald
