- name: Ensure config directory exists
  file:
    path: /var/ansible/phpmyadmin
    state: directory
    owner: root
    group: root
    mode: 0700

# uid 33 = www-data in the container
- name: Copy config.user.inc.php
  template:
    dest: /var/ansible/phpmyadmin/config.user.inc.php
    src: config.user.inc.php.j2
    owner: 33
    group: 33
    mode: 0400
  register: config_copied

- name: Get current phpmyadmin image info
  docker_image_info:
    name: "{{ phpmyadmin_image }}"
  register: phpmyadmin_image_before

- name: Pull phpmyadmin image
  docker_image:
    name: "{{ phpmyadmin_image }}"
    source: pull
  register: phpmyadmin_image_pull
  changed_when: >-
    phpmyadmin_image_before.images | length == 0 or
    phpmyadmin_image_before.images[0].Id != phpmyadmin_image_pull.image.Id

- name: Start phpmyadmin container
  docker_container:
    name: phpmyadmin
    state: started
    image: "{{ phpmyadmin_image }}"
    restart_policy: unless-stopped
    env:
      PMA_HOSTS: "mysql-1.zt.foreningenbs.no,uka-mysql.zt.foreningenbs.no,dugnaden-mysql.zt.foreningenbs.no"
      PMA_ABSOLUTE_URI: https://foreningenbs.no/tools/phpmyadmin/
      UPLOAD_LIMIT: 1024M
    networks:
      - name: fbs0
        ipv4_address: "{{ phpmyadmin_ipv4_address }}"
    networks_cli_compatible: yes
    volumes:
      - /var/ansible/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro,Z
    log_driver: journald
    restart: "{{ config_copied.changed }}"
