- name: Install service file
  copy:
    content: |
      [Unit]
      Description=DynDNS

      [Service]
      Type=oneshot
      ExecStart=/bin/sh -c '/usr/bin/wget --no-cache --spider -q "https://hsw.no/iplog/{{ fbs_dyndns_name }}?key={{ lookup('file', '../dyndns.key') }}"'
    dest: /etc/systemd/system/dyndns.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd

- name: Install timer file
  copy:
    content: |
      [Unit]
      Description=DynDNS

      [Timer]
      OnCalendar=*:0/5
      OnBootSec=15

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/dyndns.timer
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd

# Ensure systemd is reloaded if needed before continuing.
- meta: flush_handlers

- name: Enable timer
  service:
    name: dyndns.timer
    state: started
    enabled: yes
