- name: Ensure config directory exists
  file:
    path: /var/ansible/simplesamlphp
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Copy config files
  copy:
    dest: "/var/ansible/simplesamlphp/{{ item }}"
    src: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - authsources.php
    - config.php
    - php.ini
    - secrets.php
    - saml20-idp-hosted.php
    - saml20-sp-remote.php
    - secrets.php
  register: file_copied1

- name: Copy cert files
  copy:
    dest: "/var/ansible/simplesamlphp/{{ item }}"
    src: "{{ playbook_dir }}/../certs/saml/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - idp.foreningenbs.no.crt
    - idp.foreningenbs.no.key
  register: file_copied2

- name: Start simplesamlphp container
  docker_container:
    name: simplesamlphp
    state: started
    image: "{{ simplesamlphp_image }}"
    restart_policy: unless-stopped
    networks:
      - name: fbs0
        ipv4_address: "{{ simplesamlphp_ipv4_address }}"
    networks_cli_compatible: yes
    volumes:
      # PHP config.
      - /var/ansible/simplesamlphp/php.ini:/usr/local/etc/php/php.ini:Z
      # Normal config.
      - /var/ansible/simplesamlphp/authsources.php:/var/simplesamlphp/config/authsources.php:Z
      - /var/ansible/simplesamlphp/config.php:/var/simplesamlphp/config/config.php:Z
      - /var/ansible/simplesamlphp/secrets.php:/var/simplesamlphp/config/secrets.php:Z
      # Metadata.
      - /var/ansible/simplesamlphp/saml20-idp-hosted.php:/var/simplesamlphp/metadata/saml20-idp-hosted.php:Z
      - /var/ansible/simplesamlphp/saml20-sp-remote.php:/var/simplesamlphp/metadata/saml20-sp-remote.php:Z
      # Certs.
      - /var/ansible/simplesamlphp/idp.foreningenbs.no.crt:/var/simplesamlphp/cert/idp.foreningenbs.no.crt:Z
      - /var/ansible/simplesamlphp/idp.foreningenbs.no.key:/var/simplesamlphp/cert/idp.foreningenbs.no.key:Z
      # Storage.
      - /var/mnt/data/simplesamlphp-storage:/storage:z
    log_driver: journald
    restart: "{{ file_copied1.changed or file_copied2.changed }}"
