name: Build ldap-toolbox
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/ldap-toolbox.yml"
      - "services/ldap-toolbox/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: services/ldap-toolbox
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/blindern/ldap-toolbox:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          curl --fail -L -i -H "authorization: bearer $DEPLOYER_TOKEN" -H "content-type: application/json" -X POST https://deployer.foreningenbs.no/deploy -d '
          {
            "service": "ldap-toolbox",
            "attributes": {
              "image": "ghcr.io/blindern/ldap-toolbox@${{ steps.docker_build.outputs.digest }}"
            }
          }'
        env:
          DEPLOYER_TOKEN: ${{ secrets.DEPLOYER_TOKEN }}
