name: ldap-toolbox
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/ldap-toolbox.yml"
      - "services/ldap-toolbox/**"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        id: docker_build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: services/ldap-toolbox
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/blindern/ldap-toolbox:latest
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          curl -sS -i -N -L -H "authorization: bearer $DEPLOYER_TOKEN" -H "content-type: application/json" -X POST "https://deployer.foreningenbs.no/deploy?stream" -d '
          {
            "service": "ldap-toolbox",
            "attributes": {
              "image": "ghcr.io/blindern/ldap-toolbox@${{ steps.docker_build.outputs.digest }}"
            }
          }' | tee /tmp/deploy-output.txt
          tail -1 /tmp/deploy-output.txt | grep -q "DEPLOY OK"
        env:
          DEPLOYER_TOKEN: ${{ secrets.DEPLOYER_TOKEN }}
