name: Build web-1
on:
  workflow_dispatch:
  push:
    paths:
      - "services/web-1/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build container
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: services/web-1
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: blindern/internal-web-1:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          curl --fail -L -i -H "authorization: bearer $DEPLOYER_TOKEN" -H "content-type: application/json" -X POST https://deployer.foreningenbs.no/deploy -d '
          {
            "service": "web-1",
            "attributes": {
              "image": "blindern/internal-web-1@${{ steps.docker_build.outputs.digest }}"
            }
          }'
        env:
          DEPLOYER_TOKEN: ${{ secrets.DEPLOYER_TOKEN }}
