name: webdavcgi
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/webdavcgi.yml"
      - "services/webdavcgi/**"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        id: docker_build
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: services/webdavcgi
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/blindern/webdavcgi:latest
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          curl -sS -i -N -L -H "authorization: bearer $DEPLOYER_TOKEN" -H "content-type: application/json" -X POST "https://deployer.foreningenbs.no/deploy?stream" -d '
          {
            "service": "webdavcgi",
            "attributes": {
              "image": "ghcr.io/blindern/webdavcgi@${{ steps.docker_build.outputs.digest }}"
            }
          }' | tee /tmp/deploy-output.txt
          tail -1 /tmp/deploy-output.txt | grep -q "DEPLOY OK"
        env:
          DEPLOYER_TOKEN: ${{ secrets.DEPLOYER_TOKEN }}

  e2e-tests:
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      contents: read
    uses: ./.github/workflows/run-e2e-tests.yml
    with:
      tag: "@webdavcgi"
    secrets: inherit
